(define (cube-root x)
  (define (square guess)
    (* guess guess))
  (define (cube guess)
    (* guess guess guess))
  (define (improve guess)
    (/ (+ (/ x (square guess))
          (* 2 guess)) 3))
  (define (good-enough? old-guess new-guess)
    (> 0.01 (/ (abs (- new-guess old-guess))
               old-guess)))
  (define (try guess)
    (if (good-enough? guess (improve guess))
        (exact->inexact guess)
        (try (improve guess))))
  (try 1))

(cube-root 27)
