(define (sqrt x)
  (define (average n1 n2)
    (/ (+ n1 n2) 2))
  (define (square guess)
    (* guess guess))
  (define (improve guess)
    (average guess (/ x guess)))
  (define (good-enough? guess)
    (< (abs (- (square guess) x)) 0.001))
  (define (try guess)
    (if (good-enough? guess)
        (round guess)
        (try (improve guess))))
  (try 1))

(sqrt 36)
